version: "3"
services:
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel
    web:
        image: "nginx:latest"
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - app
        networks:
            - laravel
    mysql:
        image: "mysql:8.2"
        environment:
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_USER: $DB_USERNAME
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel
networks:
    laravel:

volumes:
    mysql-data: